import { useState } from "react";
import { photographyCredits } from "./photography";

export const articles = [
  { category: "MEMORY & SCENT", title: "Why Certain Scents Become Memories", text: "A photograph keeps the shape of a moment. Fragrance keeps its temperature. A trace of cedar can return us to a room we thought we had forgotten; a bitter citrus peel can bring back the light at a particular window.", second: "At our fictional house, memory is a creative material, not a promise. Velvet Reverie imagines the softness of an evening; Lunar Blossom, the stillness after dusk; Adua Aethe, a curtain moving in warm air. What they become on your skin belongs only to you." },
  { category: "THE ART OF PERFUMERY", title: "Inside the Art of Fragrance Composition", text: "Composition begins with listening. A bright opening creates space for a quieter heart; woods give the fleeting notes somewhere to rest. The work lies as much in what is removed as in what remains.", second: "In the imagined NEVORA atelier, every trial rests before it is revisited on paper and skin. Top, heart and base are not separate rooms, but overlapping passages. Explore the scent journey to hear their conversation." },
  { category: "THE FRAGRANCE", title: "The Art Behind Every Scent", text: "A fragrance is more than its notes. It is the hush of an evening, the confidence of a familiar silhouette, the warmth of a memory returning. At NEVORA, an atmosphere comes first; the composition follows.", second: "Our fictional house imagines three distinct worlds, each refined through balance, time and the way it lives on skin. Glass gives the fragrance a physical presence. The final expression belongs to the person who wears it." },
  { category: "THE HOUSE", title: "How a Fragrance Finds Its Character", text: "Character is the detail that survives silence. A peppery glimmer in a soft floral, an unexpected mineral edge, the warmth that remains when the first brightness has faded.", second: "NEVORA is an original fictional house built around three such contrasts. We imagine fragrance as something intimate rather than declarative: an invitation to notice, to wait, and to make a new memory." },
  { category: "CRAFT", title: "The Beauty of Taking Time", text: "Some gestures cannot be hurried. A blend is left to settle, a trial is revisited, and a proportion is adjusted until the composition feels effortless.", second: "Our imagined six-stage process ends with glass, a carefully fitted cap and the quiet pleasure of finishing. This is a fictional account of craft, created for the NEVORA experience." },
];

export default function ExperiencePanel({ kind, close, discover, addSet, scentIndex }: { kind: string; close: () => void; discover: (index: number) => void; addSet: () => void; scentIndex: string[] }) {
  const [query, setQuery] = useState("");
  const [category, setCategory] = useState("ALL");
  const [signedIn, setSignedIn] = useState(false);
  const [reading, setReading] = useState<number | null>(kind.startsWith("article-") ? Number(kind.split("-")[1]) : null);
  const names = ["VELVET REVERIE", "LUNAR BLOSSOM", "ADUA AETHE"];
  const article = reading === null ? null : articles[reading];
  const fragranceMatches = names.map((name, index) => ({ name, index })).filter(({ name, index }) => `${name} ${scentIndex[index]}`.toLowerCase().includes(query.toLowerCase()));
  const journalMatches = articles.filter(item => `${item.title} ${item.category}`.toLowerCase().includes(query.toLowerCase()));
  const setMatches = "discovery set the first three".includes(query.toLowerCase());
  return <div className="experience-backdrop" onClick={close}>
    <section className="experience-panel" role="dialog" aria-modal="true" aria-label={kind} onClick={event => event.stopPropagation()}>
      <button className="experience-close" aria-label="Close experience" onClick={close}>CLOSE ×</button>
      <p className="eyebrow">NEVORA · PRIVATE WORLDS</p>
      {kind === "search" && !article && <><h2>FIND A<br /><em>MEMORY.</em></h2><label className="experience-field">SEARCH THE HOUSE<input autoFocus value={query} onChange={event => setQuery(event.target.value)} placeholder="A fragrance, ingredient or story" /></label>
        {fragranceMatches.map(({ name, index }) => <button className="experience-result" key={name} onClick={() => discover(index)}>{name}<span>DISCOVER →</span></button>)}
        {setMatches && <button className="experience-result" onClick={() => { close(); document.getElementById("discovery")?.scrollIntoView(); }}>THE FIRST THREE<span>DISCOVERY SET →</span></button>}
        {journalMatches.map(item => <button className="experience-result" key={item.title} onClick={() => setReading(articles.indexOf(item))}>{item.title}<span>READ →</span></button>)}
        {!fragranceMatches.length && !journalMatches.length && !setMatches && <p className="experience-hint" role="status">No matches. Try “iris”, “Lunar”, “discovery” or “memory”.</p>}
      </>}
      {kind === "account" && <><h2>THE PRIVATE<br /><em>ARCHIVE.</em></h2>{signedIn ? <><p>Your prototype archive is open. Explore the first three compositions and begin your personal scent story.</p><button className="add-button" onClick={() => setSignedIn(false)}>SIGN OUT OF DEMO</button></> : <form onSubmit={event => { event.preventDefault(); setSignedIn(true); }}><p>A local demonstration only. No account is created and no email is sent.</p><label className="experience-field">EMAIL ADDRESS<input type="email" required placeholder="name@example.com" /></label><button className="add-button">ENTER DEMO ARCHIVE →</button></form>}</>}
      {(kind === "journal" || kind.startsWith("article-")) && !article && <><h2>NOTES FROM<br /><em>THE HOUSE.</em></h2><div className="experience-filters">{["ALL", ...new Set(articles.map(item => item.category))].map(item => <button aria-pressed={category === item} key={item} onClick={() => setCategory(item)}>{item}</button>)}</div>{articles.filter(item => category === "ALL" || item.category === category).map(item => <button className="experience-result" key={item.title} onClick={() => setReading(articles.indexOf(item))}>{item.title}<span>{item.category} →</span></button>)}</>}
      {article && <article className="journal-reading"><button className="action" onClick={() => setReading(null)}>BACK TO {kind === "search" ? "SEARCH" : "JOURNAL"}</button><p className="eyebrow">{article.category} · 3 MIN READ</p><h2>{article.title}</h2><p>{article.text}</p><p>{article.second}</p><p className="eyebrow">AN ORIGINAL FICTIONAL NEVORA EDITORIAL</p></article>}
      {kind === "discovery" && <><h2>THE FIRST<br /><em>THREE.</em></h2><p>A slow introduction to the house. Three 7.5 ml eaux de parfum, an archive box and a scent journal for your own impressions.</p>{names.map((name, index) => <button className="experience-result" key={name} onClick={() => discover(index)}>{name}<span>EXPLORE →</span></button>)}<p>3 × 7.5 ML · ₹6,800 · Complimentary delivery</p><button className="add-button" onClick={addSet}>ADD DISCOVERY SET TO BAG →</button></>}
      {["privacy", "terms", "instagram"].includes(kind) && <><h2>{kind === "privacy" ? "YOUR PRIVACY." : kind === "terms" ? "THE SMALL PRINT." : "BEYOND THE HOUSE."}</h2><p>{kind === "privacy" ? "This local prototype has no account service or payment processing. Form entries are used only for the current demonstration. Please use fictional details. External photography is served by Unsplash and fonts by Google." : kind === "terms" ? "NEVORA, its products, locations and orders are fictional. Prices are illustrative. No purchase, reservation, delivery or payment is made through this experience." : "NEVORA is a fictional house with no official social account. Explore our journal for the visual and creative stories behind the first collection."}</p></>}
      {kind === "photography" && <><h2>REAL MATERIALS.<br /><em>REAL LIGHT.</em></h2><p>Photographic references sourced from Unsplash under the Unsplash License. NEVORA names, scent compositions and branding are fictional editorial treatments; the photographs are not actual NEVORA products or workshops and imply no affiliation with their photographers.</p><p>The opening film is an editorial motion treatment of the existing perfume and campaign photography. Close-up fragrance studies are cropped from the same product references.</p>{photographyCredits.map(([name, link, subject]) => <p key={name}><a href={link} target="_blank" rel="noreferrer">{name} ↗</a><br />{subject}</p>)}<p>Botanical imagery represents either the named material or a clearly captioned sensory reference. Musk, amber and moonflower accords are not represented as harvested ingredients.</p><a href="https://unsplash.com/license" target="_blank" rel="noreferrer">UNSPLASH LICENSE ↗</a></>}
    </section>
  </div>;
}
